In [3]:
import pandas as pd

In [4]:
df_voitures  = pd.read_csv("voitures.csv",sep=';')

In [11]:
df_voitures_ = df_voitures.copy()

In [14]:
df_voitures_
df_voitures_.drop(columns = ['matricule'],inplace=True)

In [16]:
df_voitures_

      marque date_ciruclation  kilometrage  cylindre couleur  vitesse
0        BMW       12/12/2020        50000         8    noir      280
1       AUDI       01/02/2023        10000         8    noir      280
2         VW       03/02/2022        75000         6   rouge      240
3   MERCEDES       20/05/2021       100000         8   blanc      280
4         VW       31/12/2019        30000         6   jaune      260
5    PEUGEOT       14/02/2020        90000         4    gris      240
6       AUDI       01/03/2021        60000         6   rouge      260
7    FERRARI       06/06/2016       200000        12   rouge      320
8    PEUGEOT       18/05/2017       510000         3    gris      220
9         VW       19/04/2020       230000         4   blanc      220
10       BMW       19/01/2021        12300         8    bleu      280
11   BUGATTI       22/12/2022        13600        12    bleu      320
12  MERCEDES       14/07/2021       190000         8    noir      280

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
OHE = OneHotEncoder()

In [31]:
transformed = OHE.fit_transform(df_voitures_[['marque']])

In [34]:
df_ = df_voitures_.copy()

In [36]:
df_.drop(columns = ['marque'],inplace=True)

In [37]:
df_

   date_ciruclation  kilometrage  cylindre couleur  vitesse
0        12/12/2020        50000         8    noir      280
1        01/02/2023        10000         8    noir      280
2        03/02/2022        75000         6   rouge      240
3        20/05/2021       100000         8   blanc      280
4        31/12/2019        30000         6   jaune      260
5        14/02/2020        90000         4    gris      240
6        01/03/2021        60000         6   rouge      260
7        06/06/2016       200000        12   rouge      320
8        18/05/2017       510000         3    gris      220
9        19/04/2020       230000         4   blanc      220
10       19/01/2021        12300         8    bleu      280
11       22/12/2022        13600        12    bleu      320
12       14/07/2021       190000         8    noir      280

In [38]:
df_[OHE.categories_[0]] = transformed.toarray()

In [39]:
df_

,date_ciruclation,kilometrage,cylindre,couleur,vitesse,AUDI,BMW,BUGATTI,FERRARI,MERCEDES,PEUGEOT,VW
0,12/12/2020,50000,8,noir,280,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,01/02/2023,10000,8,noir,280,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,03/02/2022,75000,6,rouge,240,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,20/05/2021,100000,8,blanc,280,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,31/12/2019,30000,6,jaune,260,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,14/02/2020,90000,4,gris,240,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,01/03/2021,60000,6,rouge,260,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7,06/06/2016,200000,12,rouge,320,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,18/05/2017,510000,3,gris,220,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,19/04/2020,230000,4,blanc,220,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,19/01/2021,12300,8,bleu,280,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,22/12/2022,13600,12,bleu,320,0.0,0.0,1.0,0.0,0.0,0.0,0.0
12,14/07/2021,190000,8,noir,280,0.0,0.0,0.0,0.0,1.0,0.0,0.0