In [2]:
import pandas as pd

In [8]:
df_voitures  = pd.read_csv("voitures.csv",sep=';')

In [9]:
df_voitures

,matricule,marque,date_ciruclation,kilometrage,cylindre,couleur,vitesse
0,123,BMW,12/12/2020,50000,8,noir,280
1,124,AUDI,01/02/2023,10000,8,noir,280
2,125,VW,03/02/2022,75000,6,rouge,240
3,126,MERCEDES,20/05/2021,100000,8,blanc,280
4,127,VW,31/12/2019,30000,6,jaune,260
5,128,PEUGEOT,14/02/2020,90000,4,gris,240
6,129,AUDI,01/03/2021,60000,6,rouge,260
7,130,FERRARI,06/06/2016,200000,12,rouge,320
8,131,PEUGEOT,18/05/2017,510000,3,gris,220
9,132,VW,19/04/2020,230000,4,blanc,220
10,133,BMW,19/01/2021,12300,8,bleu,280
11,134,BUGATTI,22/12/2022,13600,12,bleu,320
12,135,MERCEDES,14/07/2021,190000,8,noir,280